name: CI
on:
  pull_request:
  push:
    branches:
      - feature/**
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [x64]
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git fetch --prune --unshallow
          git submodule update --init --recursive
      - name: Setup vcpkg
        run: .\vendor\vcpkg\bootstrap-vcpkg.bat

      - name: Install vcpkg ports
        run: |
          .\vendor\vcpkg\vcpkg.exe install boost-log:${{ matrix.arch }}-windows-static-md
          .\vendor\vcpkg\vcpkg.exe install fmt:${{ matrix.arch }}-windows-static-md
          .\vendor\vcpkg\vcpkg.exe install libtorrent:${{ matrix.arch }}-windows-static-md
          .\vendor\vcpkg\vcpkg.exe install nlohmann-json:${{ matrix.arch }}-windows-static-md
          .\vendor\vcpkg\vcpkg.exe install sqlite3:${{ matrix.arch }}-windows-static-md

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Build
        run: |
          vcpkg env
          set HTTPS_PROXY=http://127.0.0.1:10809/
          set HTTP_PROXY=http://127.0.0.1:10809/
          vcpkg install boost:x64-windowsdotnet 
          cake --platform=${{ matrix.arch }} --target=Publish --vcpkg-triplet=${{ matrix.arch }}-windows-static-md-rel

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: PicoTorrent-${{ matrix.arch }}-CI-binaries
          path: |
            build-${{ matrix.arch }}/Release/packages/PicoTorrent-*-${{ matrix.arch }}.exe
            build-${{ matrix.arch }}/Release/packages/PicoTorrent-*-${{ matrix.arch }}.zip
            build-${{ matrix.arch }}/Release/packages/PicoTorrent-*-${{ matrix.arch }}.symbols.zip
